### ISSUE TITLE
jsdocFormatExamples not working?

### ISSUE THREAD

**Issue by jasonkuhrt** [homer0/packages#11]
For example in this project prettier formatting is not working:

https://github.com/jasonkuhrt/template-typescript-lib

**Comment by homer0** [comment]
Hey Jason 👋 !

First, sorry I haven't made time for #9 ... too much work, but I didn't forget about it.

Now, the reason the tag is not being formatted it's because there's a syntax error:

```diff
 /**
  * Does the foobar thing.
  *
  * @example
  *
  * const a = foobar({
- *  a: 1
+ *  a: 1,
  *    b: 2
  * })
  *
  */
 export function foobar(): null {
   return null
 }
```

If you add that comma, it fixes the issue and the format works.

The `@example` tag actually uses Prettier under the hood... but Prettier doesn't resurface the error 😞. Even when Prettier is being used for code, not on comments, if the code is invalid, it doesn't give you an error, it just doesn't format it.

Regards!

**Comment by jasonkuhrt** [comment]
@homer0 🤦 I must have been tired, lol, thanks.
