### ISSUE TITLE
VSC and CLI don't agree

### ISSUE THREAD

**Issue by jasonkuhrt** [homer0/packages#13]
Format on save VSC:

```
 * @param name The name of the field on the Query type. Names are case‐sensitive and must conform to pattern:
 *   `[_A-Za-z][_0-9A-Za-z]*`
```

Prettier CLI run with this plugin: (`prettier --write 'src/**/*.ts' 'tests/**/*.ts' 'examples/*/src/**.ts'`)

```
 * @param name The name of the field on the Query type. Names are case‐sensitive and must conform to pattern:
 *     `[_A-Za-z][_0-9A-Za-z]*`
```

Haven't investigated, can you repro easily?

**Comment by homer0** [comment]
Hey @jasonkuhrt 👋 !

Yes, it happened to me and some of my teammates before :(...but it's always VSC that's either "forgetting the Prettier plugin config", "inheriting a global version of prettier" or "caching the previous version" :P.

I just tried to reproduce your issue and I couldn't:

1. I cloned `nexus`.
2. Installed the deps with `--frozen-lockfile`, to get the same ones you were using.
3. Went to the `queryField.ts` with VSC, and tried changing the line. It got formatted to the way it originally was.
4. I opened the file with `nano` to avoid auto formatting and changed the line.
5. Then I ran `yarn prettier --write 'src/**/*.ts' 'tests/**/*.ts' 'examples/*/src/**.ts'` (with `yarn` to ensure the local version... and because I don't have a global one :P). It got formatted to the way it originally was.

The only thing I can think of that can be different from what you have, is that I configure the Prettier plugin by repo and not globally, as I have tons of "legacy" work projects where running Prettier would be a huge mistake :P. These are the lines I usually have in my `.vscode/settings.json` to enable it:

```json
{
  "[javascript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "prettier.requireConfig": true
}
```

I would recommend you to, with VSC closed, run `rm -rf node_modules && yarn --frozen-lockfile`.

Let me know how it goes!

**Comment by homer0** [comment]
@jasonkuhrt can we close this one?

**Comment by jasonkuhrt** [comment]
@homer0 will try to look into this today! Thanks for the feedback

**Comment by jasonkuhrt** [comment]
Yep seems to be working!
