### ISSUE TITLE
Mangled markdown list formatting

### ISSUE THREAD

**Issue by jasonkuhrt** [homer0/packages#14]
Before:

![CleanShot 2021-06-25 at 23 34 39@2x](https://user-images.githubusercontent.com/284476/123500755-4296d700-d60e-11eb-9132-2a9597dcbe12.png)

After:

![CleanShot 2021-06-25 at 23 34 45@2x](https://user-images.githubusercontent.com/284476/123500751-40347d00-d60e-11eb-84c0-e4db594f1d4a.png)

**Comment by homer0** [comment]
Hey @jasonkuhrt ! I'll try to take a look this week.

**Comment by homer0** [comment]
Hey man, sorry, I haven't had enough time for this yet... but I wanted to let you know that I haven't forgotten about it.

**Comment by homer0** [comment]
Hey @jasonkuhrt ! I finally made some time to debug this :D.

I copied the text from the screenshot as input and after debugging function by function to check why it was transforming it like that, I found the issue: Add a period at the end of the sentences in the list :P.

```js
/**
 * Bema is a framework for writing benchmarks. Conceptually you can roughly think of it to benchmarks what
 * [`jest`](https://jestjs.io/) is to tests. It was initially developed at [Prisma](https://www.prisma.io/)
 * for internal benchmarking needs and continues to be used today. Its features and roadmap are driven firsly by
 * Prisma's needs however community contributions are generally welcome too!
 *
 * Features:
 *
 * 1. Runs TypeScript without you having to do anything (e.g. imagine if `jest` had [`ts-jest`](https://kulshekar.github.io/ts-jest/) builtin).
 * 2. Statically safe fluent API 3. Easy matrix definition (on par with [GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)).
 * 3. Benchmark groups.
 * 4. Benchmark parametrization (global or group level).
 * 5. CLI.
 * 6. Select benchmarks to run.
 * 7. Select benchmarks to skip.
 * 8. Target benchmarks by paramter and/or groups matches.
 * 9. GitHub Actions integration.
 * 10. Download artifcats.
 * 11. Plug GitHub matrixes into filtered benchmark runs (not actually an integrated feature at all, just works really well).
 * 12. Launch UI to visualize benchmark runs over time.
 *
 * @remarks Foobar.
 */
```

The reason it was pushing the items together was because they weren't sentences, and the code was assuming that it was a continuation of the previous line, and because it still had space in the line, it was appending it. Whenever you end a line with a period and line break, it will respect the line break.

Now, the generated output is this:

```js
/**
 * Bema is a framework for writing benchmarks. Conceptually you can roughly think of it to benchmarks what
 * [`jest`](https://jestjs.io/) is to tests. It was initially developed at [Prisma](https://www.prisma.io/)
 * for internal benchmarking needs and continues to be used today. Its features and roadmap are driven firsly
 * by Prisma's needs however community contributions are generally welcome too!
 *
 * Features:
 *
 * 1. Runs TypeScript without you having to do anything (e.g. imagine if `jest` had
 * [`ts-jest`](https://kulshekar.github.io/ts-jest/) builtin).
 * 2. Statically safe fluent API 3. Easy matrix definition (on par with [GitHub
 * Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)).
 * 3. Benchmark groups.
 * 4. Benchmark parametrization (global or group level).
 * 5. CLI.
 * 6. Select benchmarks to run.
 * 7. Select benchmarks to skip.
 * 8. Target benchmarks by paramter and/or groups matches.
 * 9. GitHub Actions integration.
 * 10. Download artifcats.
 * 11. Plug GitHub matrixes into filtered benchmark runs (not actually an integrated feature at all, just
 * works really well).
 * 12. Launch UI to visualize benchmark runs over time.
 *
 * @remarks Foobar.
 */
```

It doesn't push items together, but it breaks some lines: while it still respects the period, it will try to apply the `printWidth`, and for those lines with links, it will break in the last space before hitting the `printWidth` limit. Making it keep it in a single line would require a heavy refactor in how the function for rearranging the text works, and unfortunately, I don't currently have the time, I hope you can understand.

A couple of extra things:

- Next time send me the comment as code and the config you are overwriting :P, I had to manually copy it from the screenshot (daaamn that's a high resolution you have xD) and run a couple of checks to validate which was the `printWidth` you were using.
- "Good thing" about manually writing it... you have a typo in the first paragraph :P, it says `bencmarking` (missing an `h`).

I hope this help 🤘!

PS: I gave priority to this over the #9, because that one has a workaround and this one was breaking your comments.

**Comment by jasonkuhrt** [comment]
Thanks for looking into this! Nice to know about the trailing period workaround here.

**Comment by homer0** [comment]
@jasonkuhrt can we close this?

**Comment by jasonkuhrt** [comment]
@homer0 yep seems so, might be worth somewhere in the docs mentioning this and generally other "effective formatting techniques".

**Comment by homer0** [comment]
@jasonkuhrt Makes sense, I won't close it yet then, I'll add it to the `README` on an FAQ/Troubleshooting section.
