### ISSUE TITLE
union of literals pulls in next line

### ISSUE THREAD

**Issue by wmertens** [homer0/packages#15]
When formatting this:

```
/**
 * @typedef {{
 * 	hide?: 'narrow' | 'other'
 * 	input: never
 * }} SectionValueProps
 */
```

I get this:

```
/**
 * @typedef {{
 * 	hide?: 'narrow' | 'other'input: never
 * }} SectionValueProps
 */
```

v4.0.0

**Comment by wmertens** [comment]
as a workaround, I add a comment:
```
/**
 * @typedef {{
 * 	hide?: 'narrow' | 'other'// comment to prevent autoformat
 * 	input: never
 * }} SectionValueProps
 */
```

**Comment by homer0** [comment]
@wmertens I have to debug it, but I'm almost sure that the code inside that definition is being formatted by Prettier itself; did you try adding a colon or a semicolon?

**Comment by wmertens** [comment]
Well I have semicolons turned off so it removes them, but I presume the comments play the same role...

**Comment by homer0** [comment]
@wmertens but you can have turned off the trailing comma, but in a type definition, you need either a comma or a semicolon (this last one is for TS specifically):

```js
/**
 * @typedef {{
 * 	hide?: 'narrow' | 'other',
 * 	input: never
 * }} SectionValueProps
 */
```

If you check the [JSDoc site](https://jsdoc.app/tags-type.html), there's an example of a syntax similar to this one:

```
{{a: number, b: string, c}} myObj
```

And it uses comma as separator.

**Comment by wmertens** [comment]
Odd, intellisense works without it?

Even then, when i move the definition to the last line, so a comma would not be needed, it squashes the closing brace onto it instead of leaving it on its own line.

**Comment by homer0** [comment]
@wmertens It's odd, I just tried myself and the vscode intelligence recognizes it. Now, whatever is taking place between the curly brackets, it's actually Prettier that is formatting it, not this plugin: [`formatTypeAsCode`](https://github.com/homer0/packages/blob/main/packages/public/prettier-plugin-jsdoc/src/fns/formatTypeAsCode.js#L71).

It takes your code, transform it to make it look like a type definition:

```ts
type complex = {
  hide?: 'narrow' | 'other',
  input: never
};
```
Then formats it with Prettier; after the formatting is done, it removes the `type complex =`, the trailing semicolon and places it back into your comment.

So, unfortunately, I have no control of what type of syntax can be used inside the brackets, sorry.

**Comment by wmertens** [comment]
Aha so this is a prettier TypeScript bug?

**Comment by homer0** [comment]
@wmertens I wouldn't say it's a bug, I believe the one in "fault" here is the IDE supporting that syntax: JSDoc nor TypeScript support it, and since this plugin uses TypeScript for formatting it, it's expected that the code inside the brackets should be TypeScript compatible.

To clarify, this is not a bug, the syntax is invalid, but the IDE, somehow, is understanding it. It's pretty much like the web browsers do when they find unclosed tags, they find a way to "fix it" in order to preserve the rendering.

**Comment by wmertens** [comment]
Something is not right... When I add a comma in the JSDoc, Prettier removes it. When I try formatting the same code in a .ts file, prettier doesn't try to join fixed strings.

Here's the full JSDoc and the equivalent .ts as formatter by prettier:
```js
/**
 * @typedef {{
 * 	type?: string
 * 	value?: any
 * 	theme?: string
 * 	mapping?: {[key: string]: string}
 * 	wide?: boolean
 * 	lazy?: boolean
 * 	hide?: 'narrow' | 'other'// comment to prevent autoformat
 * 	overlap?: 'next' | 'previous'// comment to prevent autoformat
 * }} SectionValueProps
 */
```

```ts
type t = {
	type?: string
	value?: any
	theme?: string
	mapping?: {[key: string]: string}
	wide?: boolean
	lazy?: boolean
	hide?: 'narrow' | 'other'
	overlap?: 'next' | 'previous'
}
```

prettierrc:
```
{
	"arrowParens": "avoid",
	"bracketSpacing": false,
	"jsdocParser": true,
	"jsdocUseInlineCommentForASingleTagBlock": true,
	"plugins": ["./node_modules/@homer0/prettier-plugin-jsdoc"],
	"semi": false,
	"singleQuote": true,
	"trailingComma": "es5",
	"useTabs": true
}
```

**Comment by homer0** [comment]
@wmertens Found it! I didn't get it before when you said that you had semicolons off (I was thinking you had the trailing comma off, which you also have :P), but when you sent me your config, I added it to "my playground" and I found the issue.

The problem is the rule that formats string literals, it has a regular expression that uses `\s` as a possible separator, and since you are not using semicolons, it thinks `overlap` is the continuation of `other`.

Really sorry for the confusion! It was totally my fault!

I'll try to make a release as soon as possible with the fix, in the meantime, you can either [disable that particular formatting](https://github.com/homer0/packages/tree/main/packages/public/prettier-plugin-jsdoc#types-with-string-literals), or modify `src/fns/formatStringLiterals.js`, in line 65:

```diff
- const extractLiterals = (type) => R.match(/['"][\w\|\-\s'"]+['"](?:\s+)?/g, type);
+ const extractLiterals = (type) => R.match(/['"][\w\|\-\s'"]+['"](?: +)?/g, type);
```

**Comment by homer0** [comment]
@wmertens It got closed automatically by the merge of the PR, if you are still seeing the issue, please reopen, and we can keep investigating :P.

**Comment by wmertens** [comment]
Thank you so much 🎉
