### ISSUE TITLE
prettier jsdoc: Extra pipe added in long union type

### ISSUE THREAD

**Issue by anantakrishna** [homer0/packages#60]
Input:

```
        /**
         * @returns {MemoriesAlgoliaRecord | readonly MemoriesAlgoliaRecord[]}
         */
```

Output:
```
        /**
         * @returns {| MemoriesAlgoliaRecord
         *   | readonly MemoriesAlgoliaRecord[]}
         */
```

I wonder why a pipe is added before the first type in the union. It seems to be treated properly by VSCode's intellisense, but still it looks wild and unnecessary.

Plugin version: 5.1.5

**Comment by homer0** [comment]
Hi @anantakrishna!

Yeah, it's weird, but unfortunately, that's Prettier; when the type is "complex" or uses TypeScript syntax, Prettier takes care of formatting it, and when you have a union with a lot of options, or long names, it does that:

https://user-images.githubusercontent.com/6949310/209398463-08a8fde3-094a-4cfa-94ae-0fa4c385c1d0.mp4

Just to make sure, I tried running your snippet and logging _before_ and _after_ the Prettier call, and it was that:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/6949310/209398611-b27ce652-ce01-4cd0-bfa5-4d35bc6ef9ef.png">

- The extra brackets around the code are there because I didn't want to miss any possible extra white space :P
- The `type complex` is a static prefix added to the type extracted from the comment so it's a valid code Prettier can format.

I hope this is helpful to you, and sorry I can't do anything about it.
