### ISSUE TITLE
prettier-plugin-jsdoc: Can you compare and contrast the two packages a bit more?

### ISSUE THREAD

**Issue by jcbhmr** [homer0/packages#66]
I'm currently trying to figure out _what the difference is_ between [homer0/prettier-plugin-jsdoc] and [hosseinmd/prettier-plugin-jsdoc]. It seems like the differences are the following:

1. homer0 has **WAYYYY** more options (good and bad)
2. homer0 has a plugin system
3. hosseinmd has a [TSDoc] option (https://github.com/hosseinmd/prettier-plugin-jsdoc#tsdoc)
4. hosseinmd uses TypeScript and homer0 uses JavaScript

Are there any other significant differences?

If I'm right, **great!** I think other prospective users are going to have the same "wait, what are the actual differences?" moment that I had, so it'd be good to add something to the readme (I don't know your writing style/formatting preferences). If I'm wrong, then it'd be great to correct me and explain to others who will probably also get the wrong impression.

[homer0/prettier-plugin-jsdoc]: https://github.com/homer0/packages/tree/main/packages/public/prettier-plugin-jsdoc
[hosseinmd/prettier-plugin-jsdoc]: https://github.com/hosseinmd/prettier-plugin-jsdoc#readme
[tsdoc]: https://tsdoc.org/

**Comment by homer0** [comment]
@jcbhmr Hi 👋 !!

There's kind of an explanation at the end of the `README`:

> Let's start with the fact that I really like the functionality of Prettier, but I really dislike their philosophy. I understand what they are trying to achieve and it makes sense, but "just use it the way I tell you" doesn't seem like a valid solution to me.
>
> Ok, they won't accept options requests? that's perfect, it doesn't make sense to just add "one more"... but it would be great if it could be open to be extended. The only way to do it is with a plugin, which means an extra parsing.
>
> Enough ranting; I started using Prettier a couple of weeks ago and being a huge fan of JSDoc, I wanted to use it to format JSDoc blocks too, something I've doing, for sometime now, using a Node script that I was trying to make into a VSCode plugin :P.
>
> I found [prettier-plugin-jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc/) by [@hosseinmd](https://github.com/hosseinmd), but it (currently) doesn't cover most of the cases I wanted (like columns creations), it's written in TypeScript (which I don't like very much) and if I were to fork and send PRs, it could've taken forever (you can see the commits for this package), and it seemed like the perfect oportunity to try [Ramda](https://ramdajs.com/) and functional programming... so I started a new one.

(Fun fact, I'm full-on TypeScript now, [mostly due to JSDoc](https://twitter.com/homer0/status/1610845609795227650) :P)

But just to be clear, I'm not interested in competing with [hosseinmd/prettier-plugin-jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc#readme), as you can read on the quote. I built with two main ideas: to suit my use case, and to make it open & extendable to anyone with different requirements 😀. Although I'm still open to accept new cases if you open an issue, and it's something I can do :).

I'm not in a race for the "best Prettier plugin for JSDoc", so I'm not checking hosseinmd's new features, nor recommending why you should use mine instead of theirs.

I hope you can understand, and sorry if it's not what you were looking for!

PS: I was actually considering migrating it to TS, but seems that Ramda + TS only play well together with simple cases.

**Comment by jcbhmr** [comment]
Sounds good! 👍
