### ISSUE TITLE
Doesn't work when just plain text 

### ISSUE THREAD

**Issue by jasonkuhrt** [homer0/packages#9]
The following will not get formatted unless I add some tag like `@example` or `@remarks`. Seems like it should be formatted regardless.

When there is an `@description` it does not work though. So not all tags...

![image](https://user-images.githubusercontent.com/284476/110547035-5967fb00-80fd-11eb-9007-57cb52aa8394.png)

**Comment by homer0** [comment]
This is by design; it's not an all-comments formatter, it's a formatter for JSDoc blocks. The thing with the `@description` tag is that the default options, convert the contents of the tag to be the text before the other tags ([check here](https://github.com/homer0/packages/tree/master/packages/public/prettier-plugin-jsdoc#description-tag)).

I'll try to validate this week if there are no problems parsing blocks without tags and see if I can add it as an option that you would have to enable; I want the default behavior to be limited to JSDoc tags.

Regards

**Comment by jasonkuhrt** [comment]
Would be great to have an option to opt-in to formatting _everything_. Reason is, with TypeScript, sometimes (and personally I find rather often) just some explanation is needed, no types, naturally. Sure, sometimes examples are used and then we're "back on track" into identifiable JSDoc. However writing an example is often not practical (to early in a project) or warranted (an internal function).

So Just a way to opt into formatting everything would be great.

**Comment by homer0** [comment]
Hey @jasonkuhrt

Sorry for the delay on the fixes, I've been very busy lately (I just started a new job). I just released fixes for your other issues (#10), but I didn't have enough time to work on this one (the one for the table took more time than I expected).

For now, you could add `@ignore` (if you are not generating the website) or a custom tag in order for the plugin to detect it... but yeah, I'll try to add the option during this week: I started using TypeScript and I see the use case :D.

Regards

**Comment by jasonkuhrt** [comment]
Hey @homer0 any update :)

**Comment by homer0** [comment]
Hey @jasonkuhrt !

I'm so sorry, I haven't had enough time to do anything lately.

I'll try my best to get some time to work on this during next weekend.

Again, sorry, I know you have been waiting for this and you've really polite (I've seen some oss requests out there…). 

Regards.

**Comment by jasonkuhrt** [comment]
@homer0 Hey no sorry need was just a friendly check in. Thanks for all your work on this to date already. Cheers!

**Comment by homer0** [comment]
@jasonkuhrt After almost a year...  `jsdocExperimentalFormatCommentsWithoutTags`.

Sorry for the delay!
